// Embed plugins/samples/* and plugins/banner-demo into integration_test/samples_data.g.dart
// so the on-device integration test can install them without file access.
//   npx wsi-plugin build plugins/banner-demo   (from the repo root, first)
//   node integration_test/gen_samples.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', '..');
const samples = join(root, 'plugins', 'samples');
const ids = JSON.parse(readFileSync(join(samples, 'index.json'), 'utf8')).ids;
const dart = (s) => "r'''" + s.replace(/'''/g, "''' \"'''\" r'''") + "'''";

const entries = [
  ...ids.map((id) => [id, { dir: join(samples, id), files: ['plugin.json', 'main.js', 'style.css'] }]),
  ['banner-demo', {
    dir: join(root, 'plugins', 'banner-demo'),
    files: ['plugin.json', 'dist/main.js', 'style.css', 'pages/settings.html', 'pages/settings.js', 'pages/settings.css'],
  }],
];

let out = '// GENERATED by integration_test/gen_samples.mjs from plugins/samples and plugins/banner-demo. Do not edit.\n';
out += '// ignore_for_file: lines_longer_than_80_chars\n\n';
out += 'const Map<String, Map<String, String>> kSampleFiles = {\n';
for (const [id, { dir, files }] of entries) {
  out += `  '${id}': {\n`;
  for (const name of files) {
    const f = join(dir, name);
    if (!existsSync(f)) throw new Error(`missing ${f} (run wsi-plugin build first?)`);
    out += `    '${name}': ${dart(readFileSync(f, 'utf8'))},\n`;
  }
  out += '  },\n';
}
out += '};\n';
writeFileSync(join(here, 'samples_data.g.dart'), out);
console.log(`wrote samples_data.g.dart (${entries.length} plugins)`);
