// Embed plugins/samples/* into integration_test/samples_data.g.dart so the
// on-device integration test can install the 7 WSI samples without file access.
//   node integration_test/gen_samples.mjs
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const samples = join(here, '..', '..', '..', 'plugins', 'samples');
const ids = JSON.parse(readFileSync(join(samples, 'index.json'), 'utf8')).ids;
const dart = (s) => "r'''" + s.replace(/'''/g, "''' \"'''\" r'''") + "'''";

let out = `// GENERATED by integration_test/gen_samples.mjs from plugins/samples. Do not edit.\n// ignore_for_file: lines_longer_than_80_chars\n\nconst Map<String, Map<String, String>> kSampleFiles = {\n`;
for (const id of ids) {
  const dir = join(samples, id);
  out += `  '${id}': {\n`;
  for (const name of ['plugin.json', 'main.js', 'style.css']) {
    const f = join(dir, name);
    if (!existsSync(f)) continue;
    out += `    '${name}': ${dart(readFileSync(f, 'utf8'))},\n`;
  }
  out += `  },\n`;
}
out += `};\n`;
writeFileSync(join(here, 'samples_data.g.dart'), out);
console.log(`wrote samples_data.g.dart (${ids.length} samples)`);
