// GENERATED by integration_test/gen_samples.mjs from plugins/samples, plugins/banner-demo and plugins/cruise-demo. Do not edit.
// ignore_for_file: lines_longer_than_80_chars

const Map<String, Map<String, String>> kSampleFiles = {
  'hello-world': {
    'plugin.json': r'''{
  "id": "hello-world",
  "name": "Hello World",
  "version": "1.0.0",
  "description": "動作確認用のサンプルプラグイン",
  "author": "WSI Team",
  "domains": ["example.com"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "message": "Hello from WSI!"
  }
}
''',
    'main.js': r'''// WSI サンプル: Hello World
// 使用SDK: WSI.getConfig / WSI.addButton / WSI.log

// plugin.json の "config" フィールドに書いた値を読み取る
const config = WSI.getConfig();

// 画面にフローティングボタンを追加する
WSI.addButton({
  text: "👋",
  position: "bottom-right",
  onClick: () => {
    // config から読んだメッセージをダイアログ表示
    alert(config.message);
    // [WSI:hello-world] プレフィックス付きでコンソール出力
    WSI.log("ボタンがクリックされました");
  }
});

WSI.log("Hello World プラグインが読み込まれました");
''',
    'style.css': r'''.wsi-floating-button {
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}

.wsi-floating-button:hover {
  transform: scale(1.05);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
}
''',
  },
  'nipponsteel-dijaw40-csv': {
    'plugin.json': r'''{
  "id": "nipponsteel-dijaw40-csv",
  "name": "DijAW40 CSV Export",
  "version": "1.0.3",
  "description": "明細登録可能商談一覧をCSV出力するプラグイン",
  "author": "WSI Team",
  "domains": ["nipponsteel.com", "*.nipponsteel.com"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "targetPath": "/esys969/dij_web/webapp/page/DijAW40",
    "controlId": "DijAW40100201KomokuListUserControl",
    "gridId": "DijAW40100201KomokuListUserControlGrid",
    "listLabel": "明細登録可能商談一覧",
    "fileNamePrefix": "明細登録可能商談一覧"
  }
}
''',
    'main.js': r'''// WSI プラグイン: DijAW40 明細登録可能商談一覧 CSV 出力
// 使用SDK: WSI.getConfig / WSI.log / WSI.onPageLoad

(function () {
  'use strict';

  const config = WSI.getConfig();
  const TARGET_PATH = config.targetPath || '/esys969/dij_web/webapp/page/DijAW40';
  const CONTROL_ID = config.controlId || 'DijAW40100201KomokuListUserControl';
  const GRID_ID = config.gridId || 'DijAW40100201KomokuListUserControlGrid';
  const FILE_PREFIX = config.fileNamePrefix || '明細登録可能商談一覧';
  const BTN_MARKER = 'data-wsi-csv-btn';

  function isTargetPage() {
    return location.pathname === TARGET_PATH || location.pathname.endsWith('/DijAW40');
  }

  function formatTimestamp() {
    const d = new Date();
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    const h = String(d.getHours()).padStart(2, '0');
    const min = String(d.getMinutes()).padStart(2, '0');
    const sec = String(d.getSeconds()).padStart(2, '0');
    return `${y}${m}${day}_${h}${min}${sec}`;
  }

  function escapeCsv(value) {
    if (value == null) return '';
    const s = String(value);
    if (/[",\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
    return s;
  }

  function getColumnHeader(grid, col) {
    try {
      return grid.columnHeaders.getCellData(0, col, true) || grid.columns[col].header || '';
    } catch {
      return grid.columns[col]?.header || '';
    }
  }

  function getShodanAttrs(grid, rowIndex, colIndex) {
    const item = grid.rows[rowIndex]?.dataItem;
    if (item) {
      const id =
        item.shodanId ?? item.shodanid ?? item.SHODAN_ID ?? item['商談番号'] ?? '';
      const kanriId =
        item.shodanKanriId ??
        item.shodankanriid ??
        item.SHODAN_KANRI_ID ??
        item['商談管理ID'] ??
        '';
      if (id || kanriId) {
        return { shodanId: String(id || ''), shodanKanriId: String(kanriId || '') };
      }
    }

    try {
      const cell = grid.cells.getCellElement(rowIndex, colIndex);
      const link = cell?.querySelector('.js-shodanId-link');
      if (link) {
        return {
          shodanId: link.getAttribute('data-shodanid') || link.textContent.trim(),
          shodanKanriId: link.getAttribute('data-shodankanriid') || '',
        };
      }
    } catch {
      // 仮想スクロールで非表示行は DOM 未取得のことがある
    }

    return { shodanId: '', shodanKanriId: '' };
  }

  function findShodanColumnIndex(grid) {
    for (let c = 0; c < grid.columns.length; c++) {
      const header = getColumnHeader(grid, c).replace(/\s+/g, '');
      if (header.includes('商談番号')) return c;
    }
    return 0;
  }

  function exportGridToCsv(grid) {
    const colCount = grid.columns.length;
    if (colCount === 0) {
      alert('出力する列がありません。');
      return;
    }

    const shodanCol = findShodanColumnIndex(grid);
    const headers = [];
    for (let c = 0; c < colCount; c++) {
      headers.push(getColumnHeader(grid, c));
    }
    headers.push('data-shodanid', 'data-shodankanriid');

    const lines = [headers.map(escapeCsv).join(',')];
    const rowCount = grid.rows.length;

    if (rowCount === 0) {
      alert('出力するデータがありません。');
      return;
    }

    for (let r = 0; r < rowCount; r++) {
      if (grid.rows[r].isHeaderRow) continue;

      const cells = [];
      for (let c = 0; c < colCount; c++) {
        cells.push(grid.getCellData(r, c, true));
      }

      const attrs = getShodanAttrs(grid, r, shodanCol);
      cells.push(attrs.shodanId, attrs.shodanKanriId);
      lines.push(cells.map(escapeCsv).join(','));
    }

    const bom = '\uFEFF';
    const blob = new Blob([bom + lines.join('\r\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${FILE_PREFIX}_${formatTimestamp()}.csv`;
    a.click();
    URL.revokeObjectURL(url);

    WSI.log(`CSV出力完了: ${rowCount}行`);
  }

  function onExportClick() {
    const gridEl = document.getElementById(GRID_ID);
    if (!gridEl || typeof wijmo === 'undefined') {
      alert('一覧グリッドが見つかりません。ページの読み込み完了後に再度お試しください。');
      return;
    }

    const grid = wijmo.grid.FlexGrid.getControl(gridEl);
    if (!grid) {
      alert('Wijmo グリッドを取得できませんでした。');
      return;
    }

    exportGridToCsv(grid);
  }

  function injectButton(controlEl) {
    const header = controlEl.querySelector('.ControlHeader');
    if (!header || header.querySelector(`[${BTN_MARKER}]`)) return;

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'btn btn-primary btn-sm wsi-csv-export-btn';
    btn.textContent = '⬇ CSV出力';
    btn.setAttribute(BTN_MARKER, '1');
    btn.title = '一覧データをCSVファイルとしてダウンロード';
    btn.addEventListener('click', onExportClick);

    header.appendChild(btn);
    WSI.log('CSV出力ボタンを追加しました');
  }

  function tryInject() {
    if (!isTargetPage()) return;

    const controlEl = document.getElementById(CONTROL_ID);
    if (controlEl) {
      injectButton(controlEl);
    }
  }

  function startObserver() {
    if (!isTargetPage()) return;

    tryInject();

    const target = document.getElementById('Pane1') || document.getElementById('content') || document.body;
    const observer = new MutationObserver(() => tryInject());
    observer.observe(target, { childList: true, subtree: true });
  }

  WSI.onPageLoad(startObserver);
  startObserver();
})();
''',
    'style.css': r'''.ControlHeader {
  display: flex;
  align-items: center;
  gap: 8px;
}

.ControlHeader .wsi-csv-export-btn {
  display: inline-flex !important;
  align-items: center !important;
  justify-content: center !important;
  margin-left: auto;
  flex-shrink: 0;
  min-width: 100px;
  min-height: 30px;
  padding: 0 14px !important;
  font-size: 13px !important;
  font-weight: 700 !important;
  line-height: 1 !important;
  text-align: center !important;
  color: #fff !important;
  background: linear-gradient(180deg, #1a73e8 0%, #1557b0 100%) !important;
  border: 1px solid #0d47a1 !important;
  border-radius: 4px !important;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.25) !important;
  cursor: pointer !important;
  text-shadow: none !important;
  opacity: 1 !important;
  vertical-align: middle !important;
}

.ControlHeader .wsi-csv-export-btn:hover {
  background: linear-gradient(180deg, #1967d2 0%, #124a96 100%) !important;
  border-color: #0a3d8f !important;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.3) !important;
  color: #fff !important;
}

.ControlHeader .wsi-csv-export-btn:active {
  background: #124a96 !important;
  box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.2) !important;
  transform: translateY(1px);
}

.ControlHeader .wsi-csv-export-btn:focus {
  outline: 2px solid #4285f4 !important;
  outline-offset: 2px !important;
}
''',
  },
  'highlighter': {
    'plugin.json': r'''{
  "id": "highlighter",
  "name": "Highlighter",
  "version": "1.0.0",
  "description": "ページのテキストをハイライトしてURL別に永続化するプラグイン",
  "author": "WSI Team",
  "domains": ["*"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "color": "#fff59d",
    "buttonPosition": "bottom-left"
  }
}
''',
    'main.js': r'''// WSI サンプル: Highlighter
// 使用SDK: WSI.storage（get/set/remove/getAll 全部）/ WSI.addButton / WSI.getConfig
//          / WSI.onPageLoad / WSI.log
// 使用ブラウザAPI: window.getSelection / Range / TreeWalker
//
// ページ上で選択したテキストをハイライトし、WSI.storage にURL単位で保存する。
// 同じURLを再訪すると自動復元。Alt+クリックでハイライト削除。
// SPA対応（WSI.onPageLoad で URL変更を検知して再復元）。

const config = WSI.getConfig();
const color = config.color || '#fff59d';
const buttonPosition = config.buttonPosition || 'bottom-left';

// 操作フィードバック用Toast（1つだけ作って使い回す）
const toast = document.createElement('div');
toast.className = 'wsi-hl-toast';
document.body.appendChild(toast);

function showToast(message, isError) {
  toast.textContent = message;
  toast.classList.toggle('wsi-hl-toast--error', !!isError);
  toast.classList.add('wsi-hl-toast--show');
  clearTimeout(showToast._timer);
  showToast._timer = setTimeout(() => {
    toast.classList.remove('wsi-hl-toast--show');
  }, 1500);
}

// URL別の一意キー（クエリとハッシュは無視）
function pageKey() {
  return `hl:${location.origin}${location.pathname}`;
}

// span 要素を作ってハイライトとして使う
function makeHighlightSpan(id) {
  const span = document.createElement('span');
  span.className = 'wsi-highlight';
  span.style.backgroundColor = color;
  span.dataset.wsiHighlightId = id;
  span.title = 'Alt+クリックで削除';
  return span;
}

// 選択範囲をハイライトして保存
async function highlightSelection() {
  const selection = window.getSelection();
  if (!selection || selection.rangeCount === 0 || selection.toString().trim() === '') {
    showToast('テキストを選択してください', true);
    return;
  }

  const range = selection.getRangeAt(0);
  const text = selection.toString();
  const id = `hl_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
  const span = makeHighlightSpan(id);

  try {
    // surroundContents は選択が単一要素内に収まっている場合に成功する
    range.surroundContents(span);
  } catch {
    showToast('この選択範囲はハイライトできません（要素境界をまたいでいます）', true);
    return;
  }

  selection.removeAllRanges();

  // WSI.storage にURL別で保存
  const key = pageKey();
  const highlights = (await WSI.storage.get(key)) || [];
  highlights.push({ id, text, createdAt: new Date().toISOString() });
  await WSI.storage.set(key, highlights);

  showToast(`ハイライト保存（${highlights.length}件）`);
  WSI.log(`Highlighted: "${text.slice(0, 30)}..."`);
}

// 保存済みテキストを検索してハイライトspanでラップ（復元用）
function findAndWrap(searchText, id) {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode: (n) => {
      if (!n.parentElement) return NodeFilter.FILTER_REJECT;
      // 既存ハイライトや UI要素、script/styleを除外
      if (
        n.parentElement.closest(
          '.wsi-highlight, .wsi-hl-toast, .wsi-floating-button, .wsi-md-toast, .wsi-url-expander, script, style, noscript'
        )
      ) {
        return NodeFilter.FILTER_REJECT;
      }
      return n.textContent.includes(searchText)
        ? NodeFilter.FILTER_ACCEPT
        : NodeFilter.FILTER_SKIP;
    }
  });

  const node = walker.nextNode();
  if (!node) return false;

  const idx = node.textContent.indexOf(searchText);
  const range = document.createRange();
  range.setStart(node, idx);
  range.setEnd(node, idx + searchText.length);

  const span = makeHighlightSpan(id);
  try {
    range.surroundContents(span);
    return true;
  } catch {
    return false;
  }
}

// storage から読み込んで DOM に復元
async function restoreHighlights() {
  const key = pageKey();
  const highlights = (await WSI.storage.get(key)) || [];
  let ok = 0;
  let fail = 0;
  for (const hl of highlights) {
    // 二重復元防止: 既にDOMに存在するか確認
    if (document.querySelector(`[data-wsi-highlight-id="${hl.id}"]`)) {
      ok++;
      continue;
    }
    if (findAndWrap(hl.text, hl.id)) ok++;
    else {
      fail++;
      WSI.log(`Restore failed: "${hl.text.slice(0, 30)}..."`);
    }
  }
  if (highlights.length > 0) {
    WSI.log(`Restored ${ok}/${highlights.length} highlights${fail > 0 ? ` (${fail} failed)` : ''}`);
  }
}

// Alt+クリックでハイライトを削除
document.addEventListener(
  'click',
  async (e) => {
    const span = e.target.closest('.wsi-highlight');
    if (!span) return;
    if (!e.altKey) return; // Alt未押下なら無視（通常のクリック/リンク動作を妨げない）
    e.preventDefault();
    e.stopPropagation();

    const id = span.dataset.wsiHighlightId;
    const key = pageKey();
    const highlights = (await WSI.storage.get(key)) || [];
    const updated = highlights.filter((h) => h.id !== id);

    // ページのハイライトが全て消えたら、キー自体を削除してstorageをクリーンに保つ
    if (updated.length === 0) {
      await WSI.storage.remove(key);
    } else {
      await WSI.storage.set(key, updated);
    }

    // span を展開: 子ノードを親に戻して span 自体を削除
    const parent = span.parentNode;
    while (span.firstChild) parent.insertBefore(span.firstChild, span);
    parent.removeChild(span);

    showToast('ハイライト削除');
    WSI.log(`Removed highlight ${id}`);
  },
  true // capture phase でページ側のハンドラより先に実行
);

WSI.addButton({
  text: '🖍️',
  position: buttonPosition,
  onClick: highlightSelection,
});

// SPA対応: URL変更時に再復元
WSI.onPageLoad(() => {
  // DOM確定を少し待つ
  setTimeout(restoreHighlights, 500);
});

// 初回起動
(async () => {
  await restoreHighlights();

  // デモ: WSI.storage.getAll() でプラグイン全体のデータを俯瞰
  const allData = await WSI.storage.getAll();
  const totalHighlights = Object.entries(allData)
    .filter(([k]) => k.startsWith('hl:'))
    .reduce((sum, [, arr]) => sum + (Array.isArray(arr) ? arr.length : 0), 0);
  const pageCount = Object.keys(allData).filter((k) => k.startsWith('hl:')).length;
  WSI.log(`Storage overview: ${totalHighlights} highlights across ${pageCount} pages`);
})();

WSI.log('Highlighter loaded');
''',
    'style.css': r'''.wsi-highlight {
  cursor: pointer;
  padding: 1px 2px;
  border-radius: 2px;
  transition: filter 0.1s ease;
}

.wsi-highlight:hover {
  filter: brightness(0.92);
}

.wsi-hl-toast {
  position: fixed;
  top: 20px;
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 20px;
  background: rgba(67, 160, 71, 0.95);
  color: #fff;
  border-radius: 6px;
  font-size: 14px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", sans-serif;
  z-index: 2147483647;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
  opacity: 0;
  transition: opacity 0.2s ease;
  pointer-events: none;
}

.wsi-hl-toast--show {
  opacity: 1;
}

.wsi-hl-toast--error {
  background: rgba(229, 57, 53, 0.95);
}
''',
  },
  'jisho-popup': {
    'plugin.json': r'''{
  "id": "jisho-popup",
  "name": "Jisho Popup",
  "version": "1.0.0",
  "description": "日本語テキストを選択すると Jisho.org API で辞書検索するプラグイン",
  "author": "WSI Team",
  "domains": ["*"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "buttonPosition": "bottom-left",
    "panelPosition": "right",
    "panelWidth": "380px",
    "maxResults": 10,
    "maxSensesPerEntry": 3,
    "apiUrl": "https://jisho.org/api/v1/search/words"
  }
}
''',
    'main.js': r'''// WSI サンプル: Jisho Popup
// 使用SDK: WSI.fetch（GET + body パース）/ WSI.addPanel / WSI.addButton / WSI.getConfig / WSI.log
// 使用ブラウザAPI: window.getSelection
//
// 日本語テキストを選択してボタンをクリックすると、Jisho.org の公開APIで
// 辞書検索を行い、結果をサイドパネルに表示する。
//
// Jisho.org API: https://jisho.org/api/v1/search/words?keyword=<word>
// このAPIは CORS ヘッダーを返さないため、ページJSから直接は叩けない。
// WSI.fetch が Service Worker 経由で実行するため CORS 制限を回避できる。

const config = WSI.getConfig();
const buttonPosition = config.buttonPosition || 'bottom-left';
const panelPosition = config.panelPosition || 'right';
const panelWidth = config.panelWidth || '380px';
const maxResults = config.maxResults || 10;
const maxSensesPerEntry = config.maxSensesPerEntry || 3;
const apiUrl = config.apiUrl || 'https://jisho.org/api/v1/search/words';

let currentPanel = null;

// エラー通知用Toast
const toast = document.createElement('div');
toast.className = 'wsi-jisho-toast';
document.body.appendChild(toast);

function showToast(message, isError) {
  toast.textContent = message;
  toast.classList.toggle('wsi-jisho-toast--error', !!isError);
  toast.classList.add('wsi-jisho-toast--show');
  clearTimeout(showToast._timer);
  showToast._timer = setTimeout(() => {
    toast.classList.remove('wsi-jisho-toast--show');
  }, 1500);
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c]));
}

// WSI.fetch で Jisho API を叩いて JSON パース
async function lookup(word) {
  const res = await WSI.fetch(`${apiUrl}?keyword=${encodeURIComponent(word)}`, {
    method: 'GET',
  });
  if (res.error) throw new Error(res.error);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = JSON.parse(res.body);
  return data.data || [];
}

function renderEntry(entry) {
  const main = entry.japanese[0] || {};
  const kanji = main.word || main.reading || '';
  const reading = main.reading && main.word && main.reading !== main.word ? main.reading : '';

  const senses = (entry.senses || []).slice(0, maxSensesPerEntry).map((s, i) => {
    const pos = (s.parts_of_speech || []).join(', ');
    const defs = (s.english_definitions || []).join('; ');
    return `
      <div class="wsi-jisho-sense">
        <span class="wsi-jisho-num">${i + 1}.</span>
        ${pos ? `<span class="wsi-jisho-pos">${escapeHtml(pos)}</span>` : ''}
        <div class="wsi-jisho-def">${escapeHtml(defs)}</div>
      </div>
    `;
  }).join('');

  return `
    <div class="wsi-jisho-entry">
      <div class="wsi-jisho-word">
        <span class="wsi-jisho-kanji">${escapeHtml(kanji)}</span>
        ${reading ? `<span class="wsi-jisho-reading">【${escapeHtml(reading)}】</span>` : ''}
      </div>
      ${senses}
    </div>
  `;
}

function renderResults(word, entries) {
  const header = `<div class="wsi-jisho-query">🔍 ${escapeHtml(word)}</div>`;
  if (entries.length === 0) {
    return header + '<div class="wsi-jisho-empty">辞書エントリが見つかりません</div>';
  }
  const list = entries.slice(0, maxResults).map(renderEntry).join('');
  const footer = entries.length > maxResults
    ? `<div class="wsi-jisho-footer">（${entries.length}件中 ${maxResults}件を表示）</div>`
    : '';
  return header + list + footer;
}

// panel body（header の次の要素）の innerHTML を更新
function updatePanelBody(panel, html) {
  const body = panel.children[1];
  if (body) body.innerHTML = html;
}

WSI.addButton({
  text: '辞',
  position: buttonPosition,
  onClick: async () => {
    const selection = window.getSelection();
    const word = selection ? selection.toString().trim() : '';

    if (!word) {
      showToast('日本語テキストを選択してください', true);
      return;
    }

    // 既存パネルがあれば閉じてから新規作成（loading表示用）
    if (currentPanel) currentPanel.remove();
    currentPanel = WSI.addPanel({
      title: 'Jisho 辞書',
      width: panelWidth,
      position: panelPosition,
      content: `<div class="wsi-jisho-query">🔍 ${escapeHtml(word)}</div><div class="wsi-jisho-loading">検索中...</div>`,
      onClose: () => { currentPanel = null; },
    });

    try {
      const entries = await lookup(word);
      if (currentPanel) updatePanelBody(currentPanel, renderResults(word, entries));
      WSI.log(`Looked up "${word}": ${entries.length} entries`);
    } catch (err) {
      if (currentPanel) {
        updatePanelBody(
          currentPanel,
          `<div class="wsi-jisho-query">🔍 ${escapeHtml(word)}</div><div class="wsi-jisho-error">エラー: ${escapeHtml(err.message)}</div>`
        );
      }
      WSI.log(`Lookup failed for "${word}": ${err.message}`);
    }
  },
});

WSI.log('Jisho Popup loaded');
''',
    'style.css': r'''.wsi-jisho-query {
  padding: 10px 12px;
  background: #f5f5f5;
  border-radius: 4px;
  margin-bottom: 12px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", sans-serif;
  font-size: 15px;
  font-weight: 600;
  color: #333;
}

.wsi-jisho-loading,
.wsi-jisho-empty,
.wsi-jisho-error {
  padding: 20px;
  text-align: center;
  color: #888;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.wsi-jisho-error {
  color: #c62828;
}

.wsi-jisho-entry {
  padding: 12px 0;
  border-bottom: 1px solid #eee;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", "Yu Gothic", sans-serif;
}

.wsi-jisho-entry:last-child {
  border-bottom: none;
}

.wsi-jisho-word {
  margin-bottom: 6px;
}

.wsi-jisho-kanji {
  font-size: 20px;
  font-weight: 700;
  color: #222;
  margin-right: 8px;
}

.wsi-jisho-reading {
  font-size: 14px;
  color: #666;
}

.wsi-jisho-sense {
  margin: 4px 0;
  padding-left: 4px;
  font-size: 13px;
  line-height: 1.5;
}

.wsi-jisho-num {
  color: #2196f3;
  font-weight: 600;
  margin-right: 4px;
}

.wsi-jisho-pos {
  color: #888;
  font-size: 11px;
  font-style: italic;
  margin-right: 6px;
}

.wsi-jisho-def {
  color: #333;
  padding-left: 20px;
  margin-top: 2px;
}

.wsi-jisho-footer {
  color: #aaa;
  font-size: 11px;
  text-align: center;
  padding: 8px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.wsi-jisho-toast {
  position: fixed;
  top: 20px;
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 20px;
  background: rgba(67, 160, 71, 0.95);
  color: #fff;
  border-radius: 6px;
  font-size: 14px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  z-index: 2147483647;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
  opacity: 0;
  transition: opacity 0.2s ease;
  pointer-events: none;
}

.wsi-jisho-toast--show {
  opacity: 1;
}

.wsi-jisho-toast--error {
  background: rgba(229, 57, 53, 0.95);
}
''',
  },
  'markdown-copy': {
    'plugin.json': r'''{
  "id": "markdown-copy",
  "name": "Markdown Copy",
  "version": "1.0.0",
  "description": "選択したテキストをMarkdown形式でクリップボードにコピーするプラグイン",
  "author": "WSI Team",
  "domains": ["*"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "includeCitation": true,
    "buttonPosition": "bottom-right"
  }
}
''',
    'main.js': r'''// WSI サンプル: Markdown Copy
// 使用SDK: WSI.addButton / WSI.getConfig / WSI.log
// 使用ブラウザAPI: window.getSelection / Range.cloneContents / navigator.clipboard
//
// ページで選択したテキストをMarkdown形式でクリップボードにコピーする。
// <a> は [text](url)、<h1-6>/<strong>/<em>/<code>/<ul>/<ol>/<blockquote>/<img> を変換。

const config = WSI.getConfig();
const includeCitation = config.includeCitation !== false;
const buttonPosition = config.buttonPosition || 'bottom-right';

// 操作フィードバック用のToast要素（1つだけ作って使い回す）
const toast = document.createElement('div');
toast.className = 'wsi-md-toast';
document.body.appendChild(toast);

function showToast(message, isError) {
  toast.textContent = message;
  toast.classList.toggle('wsi-md-toast--error', !!isError);
  toast.classList.add('wsi-md-toast--show');
  clearTimeout(showToast._timer);
  showToast._timer = setTimeout(() => {
    toast.classList.remove('wsi-md-toast--show');
  }, 1500);
}

// DocumentFragment / Element / Text を再帰的に走査してMarkdownを生成
function nodeToMarkdown(node) {
  if (node.nodeType === Node.TEXT_NODE) return node.textContent;
  // DocumentFragment は子要素を単に連結する（wrapperを持たない）
  if (node.nodeType !== Node.ELEMENT_NODE && node.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) {
    return '';
  }

  const children = [...node.childNodes].map(nodeToMarkdown).join('');
  if (node.nodeType === Node.DOCUMENT_FRAGMENT_NODE) return children;

  const tag = node.tagName.toLowerCase();
  switch (tag) {
    case 'a': {
      // getAttribute + new URL() で相対URLを絶対URLに変換
      const href = node.getAttribute('href') || '';
      let abs = href;
      try { abs = new URL(href, document.baseURI).href; } catch {}
      return children ? `[${children}](${abs})` : '';
    }
    case 'img': {
      const src = node.getAttribute('src') || '';
      let abs = src;
      try { abs = new URL(src, document.baseURI).href; } catch {}
      const alt = node.getAttribute('alt') || '';
      return `![${alt}](${abs})`;
    }
    case 'strong': case 'b': return children ? `**${children}**` : '';
    case 'em': case 'i': return children ? `*${children}*` : '';
    case 'code':
      // <pre><code>...</code></pre> の場合は素で返し、<pre>側でフェンスを付ける
      return node.parentElement?.tagName === 'PRE' ? children : `\`${children}\``;
    case 'pre': return `\n\`\`\`\n${children}\n\`\`\`\n`;
    case 'h1': return `\n# ${children}\n`;
    case 'h2': return `\n## ${children}\n`;
    case 'h3': return `\n### ${children}\n`;
    case 'h4': return `\n#### ${children}\n`;
    case 'h5': return `\n##### ${children}\n`;
    case 'h6': return `\n###### ${children}\n`;
    case 'p': return `\n\n${children}\n\n`;
    case 'br': return '\n';
    case 'hr': return '\n---\n';
    case 'blockquote':
      return '\n' + children.trim().split('\n').map((l) => `> ${l}`).join('\n') + '\n';
    case 'li': {
      const parent = node.parentElement;
      if (parent?.tagName === 'OL') {
        const idx = [...parent.children].indexOf(node) + 1;
        return `\n${idx}. ${children.trim()}`;
      }
      return `\n- ${children.trim()}`;
    }
    case 'ul': case 'ol': return children + '\n';
    default: return children;
  }
}

// 連続する改行を整理、前後トリム
function cleanupMarkdown(md) {
  return md.replace(/\n{3,}/g, '\n\n').trim();
}

WSI.addButton({
  text: '📋 MD',
  position: buttonPosition,
  onClick: async () => {
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0 || selection.toString().trim() === '') {
      showToast('テキストを選択してください', true);
      return;
    }

    // Range.cloneContents() で選択範囲の構造を保ったDocumentFragmentが得られる
    const range = selection.getRangeAt(0);
    const fragment = range.cloneContents();

    let md = cleanupMarkdown(nodeToMarkdown(fragment));

    if (includeCitation) {
      md += `\n\n— [${document.title}](${location.href})`;
    }

    try {
      await navigator.clipboard.writeText(md);
      showToast('コピーしました ✓');
      WSI.log(`Copied ${md.length} chars as Markdown`);
    } catch (err) {
      showToast('コピー失敗: ' + err.message, true);
      WSI.log(`Copy failed: ${err.message}`);
    }
  }
});

WSI.log('Markdown Copy loaded');
''',
    'style.css': r'''.wsi-md-toast {
  position: fixed;
  top: 20px;
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 20px;
  background: rgba(67, 160, 71, 0.95);
  color: #fff;
  border-radius: 6px;
  font-size: 14px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", sans-serif;
  z-index: 2147483647;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
  opacity: 0;
  transition: opacity 0.2s ease;
  pointer-events: none;
}

.wsi-md-toast--show {
  opacity: 1;
}

.wsi-md-toast--error {
  background: rgba(229, 57, 53, 0.95);
}
''',
  },
  'outline-panel': {
    'plugin.json': r'''{
  "id": "outline-panel",
  "name": "Outline Panel",
  "version": "1.0.0",
  "description": "ページの見出しから目次を生成してサイドパネルに表示するプラグイン",
  "author": "WSI Team",
  "domains": ["*"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "buttonPosition": "top-left",
    "panelPosition": "right",
    "panelWidth": "320px"
  }
}
''',
    'main.js': r'''// WSI サンプル: Outline Panel
// 使用SDK: WSI.addPanel（主役）/ WSI.addButton / WSI.getConfig / WSI.onPageLoad / WSI.log
// 使用ブラウザAPI: querySelectorAll / Element.scrollIntoView / requestAnimationFrame
//
// ページ内の h1〜h6 見出しを収集してサイドパネルにTOC（目次）を表示する。
// クリックで該当見出しにスムーズスクロール、現在読んでいる位置を自動ハイライト。
// SPA 対応（WSI.onPageLoad で再ビルド）。

const config = WSI.getConfig();
const buttonPosition = config.buttonPosition || 'top-left';
const panelPosition = config.panelPosition || 'right';
const panelWidth = config.panelWidth || '320px';

let currentPanel = null;
let currentHeadings = [];
let scrollRafId = null;

// 表示されている見出しのみ収集（非表示要素はスキップ）
function scanHeadings() {
  return Array.from(document.querySelectorAll('h1, h2, h3, h4, h5, h6'))
    .filter((h) => {
      const text = h.textContent.trim();
      if (!text) return false;
      const rect = h.getBoundingClientRect();
      return rect.width > 0 || rect.height > 0;
    })
    .map((h, i) => {
      // スクロール先として使うため、id が無い見出しには自動生成の id を付与
      if (!h.id) h.id = `wsi-outline-auto-${i}`;
      return {
        id: h.id,
        level: parseInt(h.tagName[1], 10),
        text: h.textContent.trim(),
        element: h,
      };
    });
}

// innerHTML に渡すので必ずエスケープ（見出しに &, <, > 等が含まれる可能性）
function escapeHtml(s) {
  return s.replace(/[&<>"']/g, (c) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c]));
}

function buildPanelContent(headings) {
  if (headings.length === 0) {
    return '<div class="wsi-outline-empty">見出しが見つかりません</div>';
  }
  const items = headings
    .map((h, i) => {
      const indent = (h.level - 1) * 16;
      return `<li class="wsi-outline-item wsi-outline-l${h.level}" style="padding-left: ${indent}px"><a href="#${h.id}" data-heading-idx="${i}">${escapeHtml(h.text)}</a></li>`;
    })
    .join('');
  return `<ul class="wsi-outline-list">${items}</ul>`;
}

// 現在読んでいる位置の見出しをpanel側にハイライト表示
function updateActive() {
  if (scrollRafId) return;
  scrollRafId = requestAnimationFrame(() => {
    scrollRafId = null;
    if (!currentPanel || currentHeadings.length === 0) return;
    const triggerY = window.innerHeight * 0.3;
    let activeIdx = -1;
    for (let i = 0; i < currentHeadings.length; i++) {
      if (currentHeadings[i].element.getBoundingClientRect().top <= triggerY) {
        activeIdx = i;
      } else {
        break;
      }
    }
    currentPanel.querySelectorAll('a[data-heading-idx]').forEach((a) => {
      a.classList.toggle(
        'wsi-outline-active',
        parseInt(a.dataset.headingIdx, 10) === activeIdx
      );
    });
  });
}

function openPanel() {
  // 既にパネルが開いていれば再ビルド（ボタンが閉じる/開くのトグルではなく更新動作）
  if (currentPanel) currentPanel.remove();

  currentHeadings = scanHeadings();

  // WSI.addPanel は <div> をページに appendChild して返す
  const panel = WSI.addPanel({
    title: `目次 (${currentHeadings.length}件)`,
    width: panelWidth,
    position: panelPosition,
    content: buildPanelContent(currentHeadings),
    onClose: () => {
      currentPanel = null;
      currentHeadings = [];
    },
  });
  currentPanel = panel;

  // 各 <a> クリックで該当見出しへスムーズスクロール
  panel.querySelectorAll('a[data-heading-idx]').forEach((a) => {
    a.addEventListener('click', (e) => {
      e.preventDefault();
      const idx = parseInt(a.dataset.headingIdx, 10);
      const target = currentHeadings[idx]?.element;
      if (target) target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  });

  updateActive();
  WSI.log(`Panel opened (${currentHeadings.length} headings)`);
}

WSI.addButton({
  text: '📑',
  position: buttonPosition,
  onClick: openPanel,
});

// スクロール追従は rAF でスロットリング、passive で競合しない
window.addEventListener('scroll', updateActive, { passive: true });

// SPA: URL変更後、パネルが開いたままなら 500ms 後に再ビルド（DOM確定を待つ）
WSI.onPageLoad(() => {
  if (currentPanel) {
    setTimeout(openPanel, 500);
  }
});

WSI.log('Outline Panel loaded');
''',
    'style.css': r'''.wsi-outline-list {
  list-style: none;
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", sans-serif;
  font-size: 13px;
  line-height: 1.5;
}

.wsi-outline-item {
  margin: 0;
  padding: 0;
}

.wsi-outline-item a {
  display: block;
  padding: 6px 12px 6px 8px;
  color: #333;
  text-decoration: none;
  border-left: 3px solid transparent;
  transition: background 0.1s ease, border-color 0.1s ease;
  word-break: break-word;
}

.wsi-outline-item a:hover {
  background: #f0f0f0;
}

.wsi-outline-active {
  background: #e3f2fd !important;
  border-left-color: #2196f3 !important;
  font-weight: bold;
}

.wsi-outline-l1 {
  font-weight: 700;
  color: #000;
}

.wsi-outline-l2 {
  font-weight: 600;
}

.wsi-outline-l3 {
  font-weight: 400;
  color: #444;
}

.wsi-outline-l4,
.wsi-outline-l5,
.wsi-outline-l6 {
  font-weight: 400;
  color: #666;
  font-size: 12px;
}

.wsi-outline-empty {
  color: #888;
  text-align: center;
  padding: 40px 20px;
  font-size: 14px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", sans-serif;
}
''',
  },
  'url-expander': {
    'plugin.json': r'''{
  "id": "url-expander",
  "name": "URL Expander",
  "version": "1.0.0",
  "description": "短縮URLにホバーするとリダイレクト先を表示するプラグイン",
  "author": "WSI Team",
  "domains": ["*"],
  "scripts": {
    "main": "main.js",
    "runAt": "document_idle"
  },
  "styles": ["style.css"],
  "config": {
    "shorteners": [
      "bit.ly",
      "t.co",
      "tinyurl.com",
      "goo.gl",
      "ow.ly",
      "buff.ly",
      "is.gd",
      "lnkd.in",
      "youtu.be",
      "amzn.to",
      "fb.me",
      "dlvr.it",
      "trib.al",
      "ift.tt",
      "rebrand.ly",
      "cutt.ly",
      "short.io"
    ],
    "hoverDelayMs": 400
  }
}
''',
    'main.js': r'''// WSI サンプル: URL Expander
// 使用SDK: WSI.fetch（HEAD + redirect follow）/ WSI.getConfig / WSI.log
//
// 短縮URLリンクにホバーすると、リダイレクト先の最終URLをツールチップで表示する。
// フィッシング対策や、クリックする前に行き先を確認するためのプレビュー用途。

const config = WSI.getConfig();
const shorteners = config.shorteners || [];
const hoverDelay = config.hoverDelayMs || 400;

// 同じURLを何度もfetchしないためのメモリキャッシュ（Promiseを保存するので同時ホバーもOK）
const cache = new Map();
let hoverTimer = null;
let activeHref = null;

// ツールチップ要素は1つだけ作って使い回す
const tooltip = document.createElement('div');
tooltip.className = 'wsi-url-expander';
tooltip.setAttribute('role', 'tooltip');
document.body.appendChild(tooltip);

function isShortener(url) {
  try {
    const h = new URL(url).hostname;
    return shorteners.some((s) => h === s || h.endsWith('.' + s));
  } catch {
    return false;
  }
}

function showTooltip(text, anchor) {
  // textContent を使うことで、悪意あるURL文字列によるXSSを防ぐ
  tooltip.textContent = text;
  tooltip.style.display = 'block';
  const r = anchor.getBoundingClientRect();
  const x = Math.min(r.left, window.innerWidth - 420);
  tooltip.style.left = Math.max(8, x) + 'px';
  tooltip.style.top = r.bottom + 6 + 'px';
}

function hideTooltip() {
  tooltip.style.display = 'none';
}

function resolve(url) {
  if (cache.has(url)) return cache.get(url);

  // WSI.fetch は background.js の service worker 側で fetch() を実行するため、
  // ページのCORS制限を受けない。ここが WSI の特徴的な機能。
  const promise = (async () => {
    const res = await WSI.fetch(url, { method: 'HEAD', redirect: 'follow' });
    if (!res || res.error) return `エラー: ${(res && res.error) || '不明'}`;
    if (!res.ok) return `取得失敗 (HTTP ${res.status})`;
    if (res.redirected) return `→ ${res.url}`;
    return '(リダイレクトなし)';
  })();

  cache.set(url, promise);
  return promise;
}

document.addEventListener('mouseover', (e) => {
  const a = e.target.closest('a[href]');
  if (!a) return;
  const href = a.href;
  if (!isShortener(href)) return;

  clearTimeout(hoverTimer);
  activeHref = href;

  hoverTimer = setTimeout(async () => {
    showTooltip('🔍 解決中...', a);
    const result = await resolve(href);
    // ユーザーが既に別の場所へマウスを動かしていたら表示しない
    if (activeHref === href) showTooltip(result, a);
  }, hoverDelay);
});

document.addEventListener('mouseout', (e) => {
  const a = e.target.closest('a[href]');
  if (!a) return;
  clearTimeout(hoverTimer);
  activeHref = null;
  hideTooltip();
});

WSI.log(`URL Expander loaded (${shorteners.length} shortener domains)`);
''',
    'style.css': r'''.wsi-url-expander {
  position: fixed;
  padding: 8px 12px;
  background: rgba(30, 30, 30, 0.95);
  color: #fff;
  font-size: 12px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", sans-serif;
  border-radius: 6px;
  z-index: 2147483647;
  max-width: 400px;
  word-break: break-all;
  pointer-events: none;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.3);
  display: none;
  line-height: 1.5;
}
''',
  },
  'banner-demo': {
    'plugin.json': r'''{
  "formatVersion": 2,
  "id": "banner-demo",
  "name": "Banner Demo",
  "version": "0.1.0",
  "description": "example.com にバナーを出す。設定ページ (sheet)、メニュー、WSI.settings、自己診断の検証用",
  "author": "WSI Team",
  "domains": ["example.com"],
  "scripts": { "main": "dist/main.js", "runAt": "document_idle" },
  "styles": ["style.css"],
  "pages": {
    "settings": { "file": "pages/settings.html", "display": "sheet" }
  },
  "menu": [
    { "id": "settings", "label": "バナー設定", "type": "page", "page": "settings" },
    { "id": "visible", "label": "バナーを表示", "type": "toggle", "checked": true },
    { "type": "separator" },
    { "id": "diagnose", "label": "自己診断をログに出す", "type": "action" }
  ],
  "permissions": ["storage", "pages", "menu"],
  "settingsSchema": [
    { "key": "text", "type": "string", "label": "バナーの文言", "default": "Hello from banner-demo" },
    { "key": "color", "type": "select", "label": "色", "options": ["blue", "green", "orange"], "default": "blue" },
    { "key": "visible", "type": "boolean", "label": "表示する", "default": true }
  ],
  "config": {}
}
''',
    'dist/main.js': r'''(() => {
  var __defProp = Object.defineProperty;
  var __export = (target, all) => {
    for (var name2 in all)
      __defProp(target, name2, { get: all[name2], enumerable: true });
  };

  // plugins/banner-demo/src/features/banner.js
  var banner_exports = {};
  __export(banner_exports, {
    matches: () => matches,
    name: () => name,
    run: () => run
  });
  var name = "banner";
  function matches() {
    return true;
  }
  async function run(WSI2, ctx2) {
    const el = document.createElement("div");
    el.className = "banner-demo";
    el.setAttribute("data-banner-demo", "1");
    document.body.appendChild(el);
    const state = { text: "", color: "blue", visible: true };
    function apply() {
      el.textContent = state.text;
      el.className = `banner-demo banner-demo--${state.color}${state.visible ? "" : " banner-demo--hidden"}`;
    }
    const all = await WSI2.settings.getAll();
    Object.assign(state, all);
    apply();
    WSI2.settings.onChange(({ key, value }) => {
      state[key] = value;
      apply();
      WSI2.log(`setting ${key} = ${JSON.stringify(value)}`);
    });
    WSI2.menu.register([
      { id: "settings", label: "\u30D0\u30CA\u30FC\u8A2D\u5B9A", type: "page", page: "settings" },
      {
        id: "visible",
        label: "\u30D0\u30CA\u30FC\u3092\u8868\u793A",
        type: "toggle",
        checked: state.visible,
        onChange: (checked) => WSI2.settings.set("visible", checked)
      },
      { type: "separator" },
      { id: "diagnose", label: "\u81EA\u5DF1\u8A3A\u65AD\u3092\u30ED\u30B0\u306B\u51FA\u3059", type: "action", onSelect: diagnose }
    ]);
    WSI2.runtime.onMessage((message, sender) => {
      if (message && message.type === "ping") {
        WSI2.log(`ping from ${sender && sender.context}`);
        return { type: "pong", text: state.text };
      }
      return void 0;
    });
    function diagnose() {
      const r = el.getBoundingClientRect();
      const style = getComputedStyle(el);
      const visible = style.display !== "none" && style.visibility !== "hidden" && r.height > 0 && r.bottom > 0;
      WSI2.log(`banner: ${Math.round(r.left)},${Math.round(r.top)} ${Math.round(r.width)}x${Math.round(r.height)} visible=${visible} viewport=${window.innerWidth}x${window.innerHeight}`);
      WSI2.toast(visible ? "\u30D0\u30CA\u30FC\u306F\u8868\u793A\u3055\u308C\u3066\u3044\u307E\u3059" : "\u30D0\u30CA\u30FC\u304C\u898B\u3048\u307E\u305B\u3093");
    }
    diagnose();
    WSI2.log(`${name} ready on ${ctx2.path}`);
  }

  // plugins/banner-demo/src/main.js
  var features = [banner_exports];
  var ctx = { url: location.href, path: location.pathname, config: WSI.getConfig() };
  for (const feature of features) {
    if (!feature.matches(ctx.path)) continue;
    Promise.resolve(feature.run(WSI, ctx)).catch((e) => WSI.log(`feature ${feature.name} failed: ${e && e.message ? e.message : e}`));
  }
})();
''',
    'style.css': r'''.banner-demo {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 2147483000;
  padding: calc(10px + env(safe-area-inset-top, 0px)) 16px 10px;
  color: #fff;
  font: 600 15px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", sans-serif;
  text-align: center;
  box-shadow: 0 2px 8px rgba(0, 0, 0, .25);
  transition: transform .2s ease;
}
.banner-demo--blue { background: #4688f1; }
.banner-demo--green { background: #2e9e5b; }
.banner-demo--orange { background: #e8792b; }
.banner-demo--hidden { transform: translateY(-120%); }
''',
    'pages/settings.html': r'''<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Banner Demo settings</title>
<link rel="stylesheet" href="settings.css">
</head>
<body>
<main>
  <h1>バナー設定</h1>
  <label>文言 <input id="text" type="text" maxlength="80"></label>
  <label>色
    <select id="color">
      <option value="blue">blue</option>
      <option value="green">green</option>
      <option value="orange">orange</option>
    </select>
  </label>
  <label class="row"><input id="visible" type="checkbox"> 表示する</label>
  <p class="actions">
    <button id="ping" type="button">ページに ping</button>
    <button id="close" type="button">閉じる</button>
  </p>
  <p id="status" class="status"></p>
</main>
<script src="settings.js"></script>
</body>
</html>
''',
    'pages/settings.js': r'''// Settings page: reads / writes WSI.settings; the banner on the site page
// updates live through settings.onChange. `WSI` is on window here (plugin page).
(async function () {
  const $ = (id) => document.getElementById(id);
  const status = (t) => { $('status').textContent = t; };

  const all = await WSI.settings.getAll();
  $('text').value = all.text || '';
  $('color').value = all.color || 'blue';
  $('visible').checked = all.visible !== false;

  $('text').addEventListener('change', () => WSI.settings.set('text', $('text').value).then(() => status('文言を保存しました')));
  $('color').addEventListener('change', () => WSI.settings.set('color', $('color').value).then(() => status('色を保存しました')));
  $('visible').addEventListener('change', () => WSI.settings.set('visible', $('visible').checked).then(() => status('表示を保存しました')));

  $('ping').addEventListener('click', async () => {
    const r = await WSI.runtime.sendMessage({ type: 'ping' });
    status(r && r.reply ? `pong: ${r.reply.text} (${r.delivered} 件に配信)` : `応答なし (${r ? r.delivered : 0} 件に配信)`);
  });
  $('close').addEventListener('click', () => WSI.ui.closePage());

  WSI.log('settings page opened');
})();
''',
    'pages/settings.css': r'''body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", sans-serif; color: #222; background: transparent; }
main { padding: 16px 20px 32px; }
h1 { font-size: 18px; margin: 0 0 16px; }
label { display: block; margin: 12px 0; font-size: 14px; }
label.row { display: flex; align-items: center; gap: 8px; }
input[type=text], select { display: block; width: 100%; box-sizing: border-box; margin-top: 4px; padding: 10px; font-size: 16px; border: 1px solid #bbb; border-radius: 8px; }
.actions { display: flex; gap: 8px; margin-top: 20px; }
button { flex: 1; min-height: 44px; border: none; border-radius: 999px; background: #4688f1; color: #fff; font-size: 15px; }
#close { background: #888; }
.status { color: #666; font-size: 13px; min-height: 1.4em; }
''',
  },
  'cruise-demo': {
    'plugin.json': r'''{
  "formatVersion": 2,
  "id": "cruise-demo",
  "name": "Cruise Demo",
  "version": "0.1.0",
  "description": "ワーカーが example.com の 3 ページを順に開いて見出しを集める。tabs / onDialog / suspend-resume / navigation.intercept の検証用 (M2)",
  "author": "WSI Team",
  "domains": ["example.com"],
  "scripts": { "main": "dist/main.js", "runAt": "document_idle" },
  "background": "dist/worker.js",
  "pages": {
    "results": { "file": "pages/results.html", "display": "sheet" }
  },
  "menu": [
    { "id": "start", "label": "巡回を開始", "type": "action" },
    { "id": "stop", "label": "巡回を停止", "type": "action" },
    { "type": "separator" },
    { "id": "results", "label": "巡回結果", "type": "page", "page": "results" }
  ],
  "permissions": ["storage", "tabs", "pages", "menu", "navigation"],
  "config": {
    "urls": ["https://example.com/", "https://example.com/?page=2", "https://example.com/?page=3"],
    "stepDelayMs": 300
  }
}
''',
    'dist/main.js': r'''(() => {
  // plugins/cruise-demo/src/main.js
  WSI.log(`cruise-demo page on ${location.pathname}`);
})();
''',
    'dist/worker.js': r'''(() => {
  // plugins/cruise-demo/src/worker.js
  var STATE_KEY = "cruise";
  var config = WSI.getConfig();
  var stepDelay = Number(config.stepDelayMs) || 300;
  var paused = false;
  var stopRequested = false;
  var running = null;
  var tabId = null;
  var loaded = /* @__PURE__ */ new Map();
  var waiters = /* @__PURE__ */ new Map();
  var loadSeq = 0;
  var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  async function loadState() {
    return await WSI.storage.get(STATE_KEY) || { urls: [], index: 0, results: [], running: false };
  }
  async function saveState(state) {
    await WSI.storage.set(STATE_KEY, state);
  }
  WSI.tabs.onLoad((id, url) => {
    loaded.set(id, { url, seq: ++loadSeq });
    const resolve = waiters.get(id);
    if (resolve) {
      waiters.delete(id);
      resolve(url);
    }
  });
  function waitLoad(id, afterSeq) {
    const last = loaded.get(id);
    if (last && last.seq > afterSeq) return Promise.resolve(last.url);
    return new Promise((resolve) => waiters.set(id, resolve));
  }
  WSI.tabs.onDialog(({ tabId: id, type, message }) => {
    WSI.log(`dialog on ${id}: ${type} "${message}" -> accept`);
    return { action: "accept" };
  });
  WSI.navigation.intercept((url) => url.includes("/blocked") ? "deny" : void 0);
  async function openOrNavigate(url) {
    if (tabId) {
      const open = await WSI.tabs.list();
      if (!open.some((t) => t.tabId === tabId)) tabId = null;
    }
    const before = loadSeq;
    if (!tabId) {
      tabId = await WSI.tabs.open(url, { hidden: true });
    } else {
      await WSI.tabs.navigate(tabId, url);
    }
    await waitLoad(tabId, before);
  }
  async function step(state) {
    const url = state.urls[state.index];
    await openOrNavigate(url);
    const heading = await WSI.tabs.run(tabId, "(document.querySelector('h1') || {}).textContent || document.title");
    state.results.push({ url, heading: String(heading || "").trim(), at: (/* @__PURE__ */ new Date()).toISOString() });
    state.index += 1;
    await saveState(state);
    WSI.log(`step ${state.index}/${state.urls.length}: ${heading}`);
  }
  async function cruise() {
    const state = await loadState();
    while (state.index < state.urls.length) {
      if (stopRequested) {
        state.running = false;
        await saveState(state);
        WSI.log("stopped");
        return;
      }
      if (paused) {
        WSI.log("paused at index " + state.index);
        return;
      }
      await step(state);
      await sleep(stepDelay);
    }
    state.running = false;
    await saveState(state);
    if (tabId) {
      try {
        await WSI.tabs.close(tabId);
      } catch (e) {
      }
      tabId = null;
    }
    WSI.log(`cruise done: ${state.results.length} pages`);
    WSI.toast(`\u5DE1\u56DE\u5B8C\u4E86: ${state.results.length} \u30DA\u30FC\u30B8`);
  }
  function run() {
    if (running) return running;
    running = cruise().catch((e) => WSI.log(`cruise failed: ${e && e.message ? e.message : e}`)).finally(() => {
      running = null;
    });
    return running;
  }
  async function start(urls) {
    stopRequested = false;
    await saveState({ urls: urls && urls.length ? urls : config.urls, index: 0, results: [], running: true });
    return run();
  }
  WSI.runtime.onMessage(async (message) => {
    if (!message || typeof message !== "object") return void 0;
    if (message.type === "start") {
      start(message.urls);
      return { started: true };
    }
    if (message.type === "stop") {
      stopRequested = true;
      return { stopping: true };
    }
    if (message.type === "status") return await loadState();
    return void 0;
  });
  WSI.runtime.onSuspend(async () => {
    paused = true;
    const state = await loadState();
    WSI.log(`suspend: index=${state.index} running=${state.running}`);
  });
  WSI.runtime.onResume(async () => {
    paused = false;
    const state = await loadState();
    WSI.log(`resume: index=${state.index} running=${state.running}`);
    if (state.running && state.index < state.urls.length) run();
  });
  WSI.menu.register([
    { id: "start", label: "\u5DE1\u56DE\u3092\u958B\u59CB", type: "action", onSelect: () => start() },
    { id: "stop", label: "\u5DE1\u56DE\u3092\u505C\u6B62", type: "action", onSelect: () => {
      stopRequested = true;
    } },
    { type: "separator" },
    { id: "results", label: "\u5DE1\u56DE\u7D50\u679C", type: "page", page: "results" }
  ]);
  loadState().then((state) => {
    if (state.running && state.index < state.urls.length) {
      WSI.log(`restart: continuing from index ${state.index}`);
      run();
    }
  });
  WSI.log("cruise worker ready");
})();
''',
    'pages/results.html': r'''<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cruise results</title>
<style>
body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", sans-serif; color: #222; }
main { padding: 16px 20px 32px; }
h1 { font-size: 18px; margin: 0 0 12px; }
ol { padding-left: 20px; } li { margin: 6px 0; word-break: break-all; }
.actions { display: flex; gap: 8px; margin-top: 16px; }
button { flex: 1; min-height: 44px; border: none; border-radius: 999px; background: #4688f1; color: #fff; font-size: 15px; }
.status { color: #666; font-size: 13px; }
</style>
</head>
<body>
<main>
  <h1>巡回結果</h1>
  <p id="status" class="status"></p>
  <ol id="list"></ol>
  <p class="actions">
    <button id="start" type="button">巡回を開始</button>
    <button id="refresh" type="button">更新</button>
  </p>
</main>
<script src="results.js"></script>
</body>
</html>
''',
    'pages/results.js': r'''// Results page: reads the worker's state from WSI.storage (same plugin, same store).
(async function () {
  const $ = (id) => document.getElementById(id);
  async function render() {
    const state = (await WSI.storage.get('cruise')) || { urls: [], index: 0, results: [], running: false };
    $('status').textContent = state.running ? `巡回中 ${state.index}/${state.urls.length}` : `完了 ${state.results.length} 件`;
    $('list').innerHTML = '';
    for (const r of state.results) {
      const li = document.createElement('li');
      li.textContent = `${r.heading} — ${r.url}`;
      $('list').appendChild(li);
    }
  }
  $('start').addEventListener('click', async () => { await WSI.runtime.sendMessage({ type: 'start' }); setTimeout(render, 500); });
  $('refresh').addEventListener('click', render);
  await render();
})();
''',
  },
};
